receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus_simple:
    collection_interval: 10s
    endpoint: "host.docker.internal:8080"
    metrics_path: '/metrics'
    use_service_account: false

processors:
  batch:
    send_batch_max_size: 10000
    timeout: 1s
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
  filter/ottl:
    metrics:
      datapoint:
        - attributes["http.route"] == "/metrics"
    traces:
      span:
        - attributes["url.path"] == "/metrics"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, filter/ottl]
      exporters: [debug]
    metrics:
      receivers: [prometheus_simple]
      processors: [memory_limiter, batch, filter/ottl]
      exporters: [debug]
